name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: install
        run: yarn

      - name: build
        run: yarn build

      - name: cname (early-bird)
        run: echo "early-bird.voken.io" > ./dist/CNAME

      - name: deploy (early-bird)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken-early-bird/voken-early-bird.github.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: main
          folder: dist

      - name: cname (get)
        run: echo "get.voken.io" > ./dist/CNAME

      - name: deploy (get)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken-get/voken-get.github.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: pages
          folder: dist

      - name: clear
        run: rm -rf ./dist

      - name: build (repo)
        run: yarn build-repo

      - name: deploy (repo)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          commit-message: "@${{ github.sha }}"
          branch: gh-pages
          folder: dist
